# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.3.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
0000	0027
002A	005A
005C		
005E	007A
007C		
007E	0F39
0F3E	169A
169D	2044
2047	207C
207F	208C
208F	2307
230C	2328
232B	2767
2776	27C4
27C7	27E5
27F0	2982
2999	29D7
29DC	29FB
29FE	2E21
2E2A	3007
3012	3013
301C	FE58
FE5F	FF07
FF0A	FF3A
FF3C		
FF3E	FF5A
FF5C		
FF5E		
FF61		
FF64	10FFFF
END
